name: remote_messenger_server
services: 
  remote_server:
    image: remote_server
    container_name: remote_messenger
    ports:
      - "5101:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - db
    volumes:
      - ${HOME}/.aspnet/https:/https/
    
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment: 
      POSTGRES_PASSWORD: "MyPassword"
      POSTGRES_USERNAME: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes: 
  postgres-data:
    